sudo: false
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install -U tox-travis codecov
matrix:
    include:
    - python: "3.3"
      dist: trusty
      install:
          - pip install virtualenv==15.2.0 tox==3.1.3 tox-travis==0.10 coverage==4.5.1 codecov==2.0.15 pluggy==0.4.0 asn1crypto==0.24.0 attrs==17.4.0 Automat==0.6.0 cffi==1.11.5 constantly==15.1.0 cryptography==1.9 cssselect==1.0.1 enum34==1.1.6 frozendict==1.2 hyperlink==18.0.0 idna==2.6 incremental==17.5.0 lxml==4.2.1 nose==1.3.7 parsel==1.4.0 py==1.4.34 pyasn1==0.4.2 pyasn1-modules==0.2.1 pycparser==2.18 PyDispatcher==2.0.5 pyOpenSSL==17.2.0 pytest==3.2.5 pytest-cov==2.5.1 python-dateutil==2.7.2 queuelib==1.5.0 service-identity==17.0.0 six==1.11.0 Twisted==17.9.0 w3lib==1.19.0 xmlunittest==0.4.0 zope.interface==4.4.3
    - python: "3.4"
      dist: xenial
      install:
          - pip install virtualenv==16.6.2 tox==3.13.2 tox-travis==0.12 coverage==4.5.2 codecov==2.0.15 asn1crypto==0.24.0 atomicwrites==1.2.1 attrs==18.2.0 Automat==0.7.0 cffi==1.11.5 constantly==15.1.0 cryptography==2.5 cssselect==1.0.3 frozendict==1.2 hyperlink==18.0.0 idna==2.8 incremental==17.5.0 lxml==4.3.0 more-itertools==5.0.0 nose==1.3.7 parsel==1.5.1 pathlib2==2.3.3 py==1.7.0 pyasn1==0.4.5 pyasn1-modules==0.2.4 pycparser==2.19 PyDispatcher==2.0.5 PyHamcrest==1.9.0 pyOpenSSL==19.0.0 pytest==4.1.1 pytest-cov==2.6.1 python-dateutil==2.7.5 queuelib==1.5.0 scandir==1.9.0 service-identity==18.1.0 six==1.12.0 Twisted==18.9.0 w3lib==1.20.0 xmlunittest==0.5.0 zope.interface==4.6.0
script: tox
after_success: codecov
