sudo: false
dist: bionic
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10-dev"
jobs:
    allow_failures:
        - python: "3.10-dev"
install:
    - pip install -U pip tox-travis codecov
script: COVERAGE_FILE=.coverage tox
after_success: codecov
