sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install: 
    - pip install -U tox-travis codecov
matrix:
    include:
    - python: "3.7"
      dist: xenial
#    - python: "3.3"
#      install: 
#          - pip install -I "virtualenv<16.0" "tox<3.0" tox-travis "codecov<5.0"
script: tox
after_success: codecov
