name: Python package scrapy_rss testing
on:
  pull_request:
  push:
    branches:
      - develop
      - master
jobs:
  main-pythons-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
    - uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: .cov/.coverage*
        retention-days: 1
  coverage:
    name: Coverage combining and reporting
    needs: main-pythons-tests
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: coverage
        path: .cov
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage<5 codecov
        ls -al .cov/
    - name: Combine .coverage 
      run: |
        python -m coverage combine .cov/.coverage*
        python -m coverage xml
        python -m coverage report
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
